import SRC from "./importSongs";
import THUMB from "./importThumb";

const songs = [
    {
        id: 0,
        name: "Bắt Cóc Con Tim",
        author: "Lou Hoàng",
        url: SRC.BCCT,
        thumb: THUMB.BCCT,
    },
    {
        id: 1,
        name: "Mãi Mãi Bên Nhau",
        author: "Noo Phước Thịnh",
        url: SRC.MMBN,
        thumb: THUMB.MMBN,
    },
    {
        id: 2,
        name: "Có Ai Thương Em Như Anh (#Catena)",
        author: "Tóc Tiên",
        url: SRC.CATENA,
        thumb: THUMB.CATENA,
    },
    {
        id: 3,
        name: "Em Không Là Duy Nhất",
        author: "Tóc Tiên",
        url: SRC.EKLDN,
        thumb: THUMB.EKLDN,
    },
    {
        id: 4,
        name: "Bao Tiền Một Mớ Bình Yên?",
        author: "14 Casper; Bon",
        url: SRC.BTMMBY,
        thumb: THUMB.BTMMBY,
    },
    {
        id: 5,
        name: "Gác Lại Âu Lo",
        author: "Da LAB; Miu Lê",
        url: SRC.GLAL,
        thumb: THUMB.GLAL,
    },
    {
        id: 6,
        name: "Thanh Xuân",
        author: "Da LAB",
        url: SRC.TX,
        thumb: THUMB.TX,
    },
    {
        id: 7,
        name: "Một Nhà",
        author: "Da LAB",
        url: SRC.MN,
        thumb: THUMB.MN,
    },
    {
        id: 8,
        name: "Ngày Chưa Giông Bão",
        author: "Bùi Lan Hương",
        url: SRC.NCGB,
        thumb: THUMB.NCGB,
    },
    {
        id: 9,
        name: "Có Chàng Trai Viết Lên Cây",
        author: "Phan Mạnh Quỳnh",
        url: SRC.CCTVLC,
        thumb: THUMB.CCTVLC,
    },
    {
        id: 10,
        name: "Bước Qua Nhau",
        author: "Vũ",
        url: SRC.BQN,
        thumb: THUMB.BQN,
    },
    {
        id: 11,
        name: "Anh Đếch Cần Gì Nhiều Ngoài Em",
        author: "Đen; Vũ; Thành Đồng",
        url: SRC.ADCGNNE,
        thumb: THUMB.ADCGNNE,
    },
    {
        id: 12,
        name: "Lạ Lùng",
        author: "Vũ",
        url: SRC.LL,
        thumb: THUMB.LL,
    },
    {
        id: 13,
        name: "Bước Qua Mùa Cô Đơn",
        author: "Vũ",
        url: SRC.BQMCD,
        thumb: THUMB.BQMCD,
    },
    {
        id: 14,
        name: "Thằng Điên",
        author: "JustaTee; Phương Ly",
        url: SRC.TD,
        thumb: THUMB.TD,
    },
    {
        id: 15,
        name: "Mặt Trời Của Em",
        author: "Phương Ly; JustaTee",
        url: SRC.MTCE,
        thumb: THUMB.MTCE,
    },
    {
        id: 16,
        name: "Nơi Mình Dừng Chân",
        author: "Mỹ Tâm",
        url: SRC.NMDC,
        thumb: THUMB.NMDC,
    },
    {
        id: 17,
        name: "Không Sao Mà Em Đây Rồi",
        author: "Suni Hạ Linh; Lou Hoàng",
        url: SRC.KSMEDR,
        thumb: THUMB.KSMEDR,
    },
    {
        id: 18,
        name: "Tìm Lại Bầu Trời",
        author: "Tuấn Hưng",
        url: SRC.TLBT,
        thumb: THUMB.TLBT,
    },
    {
        id: 19,
        name: "Nắm Lấy Tay Anh",
        author: "Tuấn Hưng",
        url: SRC.NLTA,
        thumb: THUMB.NLTA,
    },
];

export default songs;
